### ISSUE TITLE
Hello Yusha

### ISSUE THREAD

**Issue by dchen278** [Jayfiul/githubTest#1]

**Comment by Jayfiul** [comment]
Yes so what is the concern?

**Comment by dchen278** [comment]
I am concerned about my concern

**Comment by Jayfiul** [comment]
Damn so how can i fix it?

**Comment by dchen278** [comment]
You can fix it by following the instructions in the email I sent yesterday.

**Comment by Jayfiul** [comment]
Kind sir can u resend the email?

**Comment by dchen278** [comment]
Sure! I just resent it!

**Comment by Jayfiul** [comment]
Can u copy and paste it here. I still didn't receive it?

**Comment by dchen278** [comment]
Dear Yusha, 

[REDACTED]

Hope you can address my concern!

Yours Truly, 
David Chen

**Comment by Jayfiul** [comment]
Hey so I actually cant see it, i think u copied the wrong email?

**Comment by dchen278** [comment]
Hey so the email contains sensitive content, so I cannot reveal the information over Github Issues. Can you let me know what time you are free to come over to my house?

**Comment by Jayfiul** [comment]
Ummmm, can i bring toys?

**Comment by dchen278** [comment]
Of course, you can bring anything you want!

**Comment by Jayfiul** [comment]
Can i bring my girlfriends?

**Comment by dchen278** [comment]
May I inquire how many girlfriends you have?

**Comment by Jayfiul** [comment]
`f(x) = 10x - 1` I have f'(x) gfs

**Comment by dchen278** [comment]
So what is x?

**Comment by Jayfiul** [comment]
let me clarify, i mean `f'(x)`

**Comment by dchen278** [comment]
Do you think they will fit in my 200 sqft house

**Comment by Jayfiul** [comment]
nah can we book an air bnb?

**Comment by dchen278** [comment]
Sure, kind sir! Let me know where

**Comment by Jayfiul** [comment]
ur supposed to book it?

**Comment by thunder-red-star** [comment]
~~screenshots taken~~

**Comment by dchen278** [comment]
> ~~screenshots taken~~

Sir, please kindly redact our names if you do decide to share it.

**Comment by thunder-red-star** [comment]
I always do that :)

**Comment by dchen278** [comment]
> I always do that :)

Anyways, do you have any concerns for Yusha to address?

**Comment by thunder-red-star** [comment]
Not really, this just came up on my github dashboard so yes

**Comment by Jayfiul** [comment]
guys please use high cognitive preguntas.

**Comment by dchen278** [comment]
Yusha, you still did not answer my question

**Comment by Jayfiul** [comment]
so what was the question again?
